- name: Run Powershell Scripts
  hosts: winservers
  tasks:
    - name: run a powershell script
      script: /home/abhishekt/vm_vagrant_ansible/vm_create.ps1
      register: out
    - debug: var=out
