"""empty message

Revision ID: 26605908af4d
Revises: d0e506451f28
Create Date: 2020-07-28 22:59:03.738721

"""

# revision identifiers, used by Alembic.
revision = '26605908af4d'
down_revision = 'd0e506451f28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=255), nullable=True),
    sa.Column('envoiroment', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=True),
    sa.Column('instance_type', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('instance_name', sa.String(length=255), nullable=True),
    sa.Column('machine_username', sa.String(length=255), nullable=True),
    sa.Column('ram_size', sa.String(length=255), nullable=True),
    sa.Column('storage_size', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    ### end Alembic commands ###
