"""empty message

Revision ID: 6a764ff2bb10
Revises: f5b0aacad35c
Create Date: 2020-07-28 23:16:55.789490

"""

# revision identifiers, used by Alembic.
revision = '6a764ff2bb10'
down_revision = 'f5b0aacad35c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('assigned_to', sa.String(length=255), nullable=True))
    op.add_column('ticket', sa.Column('issued_by', sa.String(length=255), nullable=True))
    op.add_column('ticket', sa.Column('status', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'status')
    op.drop_column('ticket', 'issued_by')
    op.drop_column('ticket', 'assigned_to')
    ### end Alembic commands ###
