"""empty message

Revision ID: 9f989c2f11ca
Revises: 6a764ff2bb10
Create Date: 2020-07-28 23:17:39.296674

"""

# revision identifiers, used by Alembic.
revision = '9f989c2f11ca'
down_revision = '6a764ff2bb10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
