"""empty message

Revision ID: 9ffe16757c71
Revises: 9f989c2f11ca
Create Date: 2020-07-28 23:20:05.468090

"""

# revision identifiers, used by Alembic.
revision = '9ffe16757c71'
down_revision = '9f989c2f11ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('ticket', sa.Column('type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'type')
    op.drop_column('ticket', 'description')
    ### end Alembic commands ###
