"""empty message

Revision ID: c8850392b771
Revises: 9ffe16757c71
Create Date: 2020-07-28 23:20:11.258564

"""

# revision identifiers, used by Alembic.
revision = 'c8850392b771'
down_revision = '9ffe16757c71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
