"""empty message

Revision ID: d0e506451f28
Revises: a7bca515a457
Create Date: 2020-07-06 15:25:16.521802

"""

# revision identifiers, used by Alembic.
revision = 'd0e506451f28'
down_revision = 'a7bca515a457'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
