"""empty message

Revision ID: f5b0aacad35c
Revises: 95e3b2c18f83
Create Date: 2020-07-28 23:16:00.732023

"""

# revision identifiers, used by Alembic.
revision = 'f5b0aacad35c'
down_revision = '95e3b2c18f83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
