---
- name: Provision VM
  hosts: 10.11.14.18
  gather_facts: no
  vars_files:
    - vars/win_cmd.yml
  tasks:
    - import_tasks: tasks/prov_vm.yml
    - pause:
        minutes: 2  
    - name: Copy and Execute the script
      win_shell: "{{ win_command }}"
      register: homedir_out
    - debug:
        var: homedir_out.stdout_lines[3].split(',')[0].replace('{','') 

    #- name: Call API
      #uri:
        #url: http://10.11.26.219/api/v2/job_templates/51/launch/
        #user: admin
        #password: passowrd
        #method: POST
        #body: 
        #- [ --extra-vars, 10.11.14.88]
        #force_basic_auth: yes
        #status_code: 201
        #body_format: json

    - name: Sending an e-mail using Gmail SMTP servers
      mail:
          host: smtp.gmail.com
          port: 587
          username: santoshkolekar99@gmail.com
          password: gysepwqiwfpuuttw
          to: "{{ to }}"
          subject: Virtual Machine Details report
          body:
            "Dear User,\n
            please find the below virtual machine details.\n\n
            public_ip: {{ homedir_out.stdout_lines[3].split(',')[0].replace('{','') }}\n
            user_name: Administrator\n
            Password: Nitor@123\n\n
            Regards,\n
            System Admin\n"
      delegate_to: localhost      
