---
- name: Provision VM
  hosts: 10.11.14.18
  gather_facts: no
  vars_files:
    - vars/win_cmd.yml
  tasks:
    - import_tasks: tasks/prov_vm.yml
    - pause:
        minutes: 2  
    - name: Copy and Execute the script
      win_shell: "{{ win_command }}"
      register: homedir_out
    - debug:
        ip_var: homedir_out.stdout_lines[3].split(',')[0].replace('{','')
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
          host: smtp.gmail.com
          port: 587
          username: santoshkolekar99@gmail.com
          password: gysepwqiwfpuuttw
          to: "{{ to }}"
          subject: Virtual Machine Details report
          body:
            "Dear User,\n
            please find the below virtual machine details.\n\n
            public_ip: {{ homedir_out.stdout_lines[3].split(',')[0].replace('{','') }}\n
            user_name: Administrator\n
            Password: Nitor@123\n\n
            Regards,\n
            System Admin\n"
      delegate_to: localhost
- name: add a host alias that we reach through a tunnel
  add_host:
    hostname: "{{ ip_var }}"
    ansible_ssh_user: Administrator
    ansible_ssh_pass: Nitor@123
    ansible_ssh_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_scheme: http
    ansible_winrm_kerberos_delegation: true
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: install java
      win_package:
        path: c:\\software\\jdk-15.0.1_windows-x64_bin.exe
        product_id: jdk-7u2
        arguments:
          - /s
          - /quiet
        state: present 
    - name: Add JAVA_HOME Env
      win_path:
        name: JAVA_HOME
        elements: C:\Program Files\Java\jdk1.7.0_02
        scope: machine
        state: present
    - name: Add JAVA_BIN Env
      win_path:
        name: PATH
        elements: C:\Program Files\Java\jdk1.7.0_02\bin
        scope: machine
        state: present
    - name: check jdk shell 
      win_shell: "java -version"
      args:
        executable: cmd
      register: java_version
    - debug: msg="{{java_version.stderr_lines}}"   
