---
- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:

  - name: Create required security groups
    ec2_group:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ item.rules }}"
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
    with_items: "{{security_groups}}"

  - name: Launch instances
    ec2: 
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ keypair }}"
      group: "{{ item.group }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ item.image }}"
      instance_tags: "{{ item.instance_tags }}"
      exact_count: "{{ item.exact_count }}"
      count_tag: "{{ item.count_tag }}"
      wait: "{{ item.wait }}"
      wait_timeout: "{{ item.wait_timeout }}"
    register: ec2

    with_items: "{{ ec2_instances }}"

  - pause:
      minutes: 1
  - name: Get EC2 Info
    ec2_instance_info:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      filters:
        "tag:Name":  "{{ tag_name }}"
    register: ec2_metadata 
 
  - name: Get instance IP addresses
    debug: 
      msg:
        - "{{ ec2_metadata.instances[0].instance_id }}"
  - pause:
      minutes: 5  

  - name: get the Administrator password
    ec2_win_password:
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      instance_id: "{{ ec2_metadata.instances[0].instance_id }}"
      region: "{{ ec2_region }}" 
      key_file: "/var/lib/awx/projects/aws_vm_provisioning_windows_email/LinuxKeyAWS.pem"
    register: result
  - debug : 
      msg: "{{ result.win_password }}"

  - name: Sending an e-mail using Gmail SMTP servers
    mail:
        host: smtp.gmail.com
        port: 587
        username: santoshkolekar99@gmail.com
        password: gysepwqiwfpuuttw
        to: "{{ to }}"
        subject: EC2 Instance Details report
        body:
          "Dear User,\n
          please find the below ec2 instance details.\n\n
          public_ip: {{ ec2_metadata.instances[0].public_ip_address }}\n
          instance_id: {{ ec2_metadata.instances[0].instance_id }}\n
          instance_type: {{ ec2_metadata.instances[0].instance_type }}\n
          launch_time: {{ ec2_metadata.instances[0].launch_time }}\n
          key_name: {{ ec2_metadata.instances[0].key_name }}\n
          user_name: {{ user_name }}\n
          password: {{ result.win_password }}\n\n
          Regards,\n  
          System Admin\n"
    delegate_to: localhost

       

