export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';


export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAILURE = 'CREATE_TICKET_FAILURE';
export const CREATE_TICKET_REQUEST = 'CREATE_TICKET_REQUEST';


export const APPROVE_TICKET_SUCCESS = 'APPROVE_TICKET_SUCCESS';
export const APPROVE_TICKET_FAILURE = 'APPROVE_TICKET_FAILURE';
export const APPROVE_TICKET_REQUEST = 'APPROVE_TICKET_REQUEST';

export const FETCH_TICKET_DATA_REQUEST = 'FETCH_TICKET_DATA_REQUEST';
export const RECEIVE_TICKET_DATA = 'RECEIVE_TICKET_DATA';
