vms:
  - type: winservers 
    name: "{{ vm_name }}"

    cpu: 2   
    memory: "{{ memory }}"

    #network:
      #ip: 10.11.14.19
      #netmask: 255.255.255.0
      #gateway: 10.11.14.1
      #dns: 10.11.12.11
      
    network_switch: 'Guest Virtual Switch' 

    src_vhd: "D:\\Packer\\packer-templates\\output-hyperv-iso\\Virtual Hard Disks\\packer-hyperv-iso.vhdx"
    dest_vhd: "C:\\Users\\Public\\Documents\\Hyper-V\\Virtual hard disks\\packer-hyperv-iso.vhdx"
    #img_path: "D:\\software\\9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO"
